import {
    ENUM_POLICY_ROLE_TYPE,
    ENUM_POLICY_SUBJECT,
} from 'src/modules/policy/enums/policy.enum';

export const ROLE_DEFAULT_AVAILABLE_SEARCH = ['name'];
export const ROLE_DEFAULT_IS_ACTIVE = [true, false];
export const ROLE_DEFAULT_POLICY_ROLE_TYPE = Object.values(
    ENUM_POLICY_ROLE_TYPE
);

export const ALLOWED_WORKSPACE_POLICY_SUBJECT: ENUM_POLICY_SUBJECT[] = [
    ENUM_POLICY_SUBJECT.ACTIVITY,
    ENUM_POLICY_SUBJECT.UTILITIES,
    ENUM_POLICY_SUBJECT.DASHBOARD,
    ENUM_POLICY_SUBJECT.WORKSPACE,
    ENUM_POLICY_SUBJECT.USER,
    ENUM_POLICY_SUBJECT.MEMBER,
    ENUM_POLICY_SUBJECT.CHATBOT,
    ENUM_POLICY_SUBJECT.RAG,
    ENUM_POLICY_SUBJECT.KNOWLEDGE_BASE,
    ENUM_POLICY_SUBJECT.TOOL,
    ENUM_POLICY_SUBJECT.CUSTOMER,
    ENUM_POLICY_SUBJECT.CLIENT_CREDENTIAL,
    ENUM_POLICY_SUBJECT.SKILL,
    ENUM_POLICY_SUBJECT.TOKEN_USAGE,
];

export const ALLOWED_MEMBER_WORKSPACE_POLICY_SUBJECT: ENUM_POLICY_SUBJECT[] = [
    ENUM_POLICY_SUBJECT.CHATBOT,
    ENUM_POLICY_SUBJECT.RAG,
    ENUM_POLICY_SUBJECT.KNOWLEDGE_BASE,
    ENUM_POLICY_SUBJECT.CUSTOMER,
];
export const ALLOWED_ADMIN_WORKSPACE_POLICY_SUBJECT: ENUM_POLICY_SUBJECT[] = [
    ENUM_POLICY_SUBJECT.DASHBOARD,
    ENUM_POLICY_SUBJECT.WORKSPACE,
    ENUM_POLICY_SUBJECT.MEMBER,
    ENUM_POLICY_SUBJECT.CHATBOT,
    ENUM_POLICY_SUBJECT.RAG,
    ENUM_POLICY_SUBJECT.KNOWLEDGE_BASE,
    ENUM_POLICY_SUBJECT.TOOL,
    ENUM_POLICY_SUBJECT.CUSTOMER,
    ENUM_POLICY_SUBJECT.CLIENT_CREDENTIAL,
    ENUM_POLICY_SUBJECT.SKILL,
    ENUM_POLICY_SUBJECT.TOKEN_USAGE,
];
