import type { BusinessTypeId } from "./business-types";
import type { CollectId, FactId, GoalId, RuleId } from "./libraries";

export type Preset = { goals: GoalId[]; rules: RuleId[]; facts: FactId[]; collect: CollectId[] };

export const PRESETS: Record<BusinessTypeId, Preset> = {
  restaurant: { goals: ["answer_questions", "reservations", "take_orders", "promotions"], rules: ["no_invented_prices", "no_discount_promises"], facts: ["opening_hours", "address", "menu_highlights", "reservation_policy", "delivery", "payment_methods"], collect: ["name", "phone", "date_time", "party_size"] },
  beauty: { goals: ["answer_questions", "recommend", "book_appointments", "promotions"], rules: ["no_invented_prices", "no_medical_advice", "no_guarantees"], facts: ["services_prices", "opening_hours", "address", "deposit_policy", "payment_methods"], collect: ["name", "phone", "date_time", "product_interest"] },
  healthcare: { goals: ["answer_questions", "book_appointments", "capture_leads"], rules: ["no_medical_advice", "no_invented_prices", "no_guarantees", "no_personal_data_requests"], facts: ["services_prices", "doctors_specialties", "opening_hours", "address", "insurance_accepted", "deposit_policy"], collect: ["name", "phone", "date_time", "notes"] },
  fashion: { goals: ["answer_questions", "recommend", "take_orders", "order_status", "after_sales"], rules: ["no_invented_prices", "no_discount_promises"], facts: ["size_guide", "shipping_fee", "return_policy", "payment_methods", "stock_updates"], collect: ["name", "phone", "address", "product_interest"] },
  cosmetics: { goals: ["answer_questions", "recommend", "take_orders", "after_sales"], rules: ["no_invented_prices", "no_health_claims", "no_medical_advice"], facts: ["skin_types", "authenticity", "shipping_fee", "return_policy", "payment_methods"], collect: ["name", "phone", "address", "product_interest"] },
  ecommerce: { goals: ["answer_questions", "recommend", "take_orders", "order_status", "after_sales", "promotions"], rules: ["no_invented_prices", "no_discount_promises"], facts: ["shipping_fee", "delivery", "payment_methods", "return_policy", "warranty"], collect: ["name", "phone", "address", "product_interest"] },
  real_estate: { goals: ["answer_questions", "qualify_leads", "book_appointments", "capture_leads"], rules: ["no_invented_prices", "no_financial_advice", "no_guarantees"], facts: ["projects", "price_range", "address", "payment_methods"], collect: ["name", "phone", "budget", "date_time"] },
  education: { goals: ["answer_questions", "recommend", "capture_leads", "book_appointments"], rules: ["no_invented_prices", "no_guarantees"], facts: ["courses", "schedule", "level_test", "services_prices", "address"], collect: ["name", "phone", "email", "product_interest"] },
  hotel: { goals: ["answer_questions", "reservations", "promotions"], rules: ["no_invented_prices", "no_discount_promises"], facts: ["room_types", "checkin_policy", "deposit_policy", "address", "payment_methods"], collect: ["name", "phone", "date_time", "party_size"] },
  travel: { goals: ["answer_questions", "recommend", "qualify_leads", "capture_leads"], rules: ["no_invented_prices", "no_guarantees"], facts: ["tour_packages", "visa_support", "deposit_policy", "payment_methods"], collect: ["name", "phone", "date_time", "party_size", "budget"] },
  fitness: { goals: ["answer_questions", "book_appointments", "capture_leads", "promotions"], rules: ["no_invented_prices", "no_medical_advice", "no_guarantees"], facts: ["membership_plans", "trial_class", "schedule", "opening_hours", "address"], collect: ["name", "phone", "date_time"] },
  automotive: { goals: ["answer_questions", "book_appointments", "qualify_leads", "capture_leads"], rules: ["no_invented_prices", "no_discount_promises", "no_financial_advice"], facts: ["car_models", "test_drive", "service_booking", "address", "opening_hours"], collect: ["name", "phone", "date_time", "product_interest"] },
  finance: { goals: ["answer_questions", "qualify_leads", "capture_leads"], rules: ["no_financial_advice", "no_guarantees", "no_personal_data_requests"], facts: ["products_plans", "eligibility", "opening_hours"], collect: ["name", "phone", "product_interest"] },
  home_services: { goals: ["answer_questions", "book_appointments", "capture_leads"], rules: ["no_invented_prices", "no_guarantees"], facts: ["services_offered", "service_area", "quote_process", "warranty"], collect: ["name", "phone", "address", "date_time"] },
  studio_events: { goals: ["answer_questions", "recommend", "book_appointments", "capture_leads"], rules: ["no_invented_prices", "no_discount_promises"], facts: ["packages", "booking_lead_time", "deposit_policy", "address"], collect: ["name", "phone", "date_time", "budget"] },
  health_foods: { goals: ["answer_questions", "recommend", "take_orders"], rules: ["no_health_claims", "no_medical_advice", "no_invented_prices"], facts: ["key_ingredients", "certifications", "shipping_fee", "payment_methods"], collect: ["name", "phone", "address", "product_interest"] },
  personal_scheduling: { goals: ["manage_schedule"], rules: ["confirm_before_acting", "no_personal_data_requests"], facts: ["working_hours", "priorities"], collect: [] },
  personal_email: { goals: ["triage_email"], rules: ["confirm_before_acting"], facts: ["email_rules", "priorities"], collect: [] },
  personal_tasks: { goals: ["track_tasks"], rules: ["confirm_before_acting"], facts: ["reminder_style", "priorities", "working_hours"], collect: [] },
  personal_research: { goals: ["research"], rules: ["no_guarantees"], facts: ["sources", "priorities"], collect: [] },
  personal_crm: { goals: ["log_contacts", "capture_leads"], rules: ["confirm_before_acting", "no_personal_data_requests"], facts: ["followup_cadence", "priorities"], collect: [] },
};
