import { Migration } from '@mikro-orm/migrations';

// Data only: sign-up requires a country, and deployments seeded before this
// had only Indonesia. Inserts every ISO 3166-1 country (a snapshot of
// src/migration/data/country.data.ts); rows that already exist are left as
// they are. No schema change.
export class Migration20260929120000_seed_countries extends Migration {

  override async up(): Promise<void> {
    this.addSql(`insert into "countries" ("name", "alpha2code", "alpha3code", "numeric_code", "phone_code", "continent", "time_zone", "currency") values
        ('Andorra', 'AD', 'AND', '020', '["376"]', 'Europe', 'Europe/Andorra', 'EUR'),
        ('United Arab Emirates', 'AE', 'ARE', '784', '["971"]', 'Asia', 'Asia/Dubai', 'AED'),
        ('Afghanistan', 'AF', 'AFG', '004', '["93"]', 'Asia', 'Asia/Kabul', 'AFN'),
        ('Antigua and Barbuda', 'AG', 'ATG', '028', '["1268"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Anguilla', 'AI', 'AIA', '660', '["1264"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Albania', 'AL', 'ALB', '008', '["355"]', 'Europe', 'Europe/Tirane', 'ALL'),
        ('Armenia', 'AM', 'ARM', '051', '["374"]', 'Asia', 'Asia/Yerevan', 'AMD'),
        ('Angola', 'AO', 'AGO', '024', '["244"]', 'Africa', 'Africa/Luanda', 'AOA'),
        ('Antarctica', 'AQ', 'ATA', '010', '["672"]', 'Antarctica', 'UTC', ''),
        ('Argentina', 'AR', 'ARG', '032', '["54"]', 'South America', 'America/Argentina/Buenos_Aires', 'ARS'),
        ('American Samoa', 'AS', 'ASM', '016', '["1684"]', 'Oceania', 'Pacific/Pago_Pago', 'USD'),
        ('Austria', 'AT', 'AUT', '040', '["43"]', 'Europe', 'Europe/Vienna', 'EUR'),
        ('Australia', 'AU', 'AUS', '036', '["61"]', 'Oceania', 'Australia/Sydney', 'AUD'),
        ('Aruba', 'AW', 'ABW', '533', '["297"]', 'North America', 'America/Puerto_Rico', 'AWG'),
        ('Aland', 'AX', 'ALA', '248', '["358"]', 'Europe', 'Europe/Mariehamn', 'EUR'),
        ('Azerbaijan', 'AZ', 'AZE', '031', '["994"]', 'Asia', 'Asia/Baku', 'AZN'),
        ('Bosnia and Herzegovina', 'BA', 'BIH', '070', '["387"]', 'Europe', 'Europe/Sarajevo', 'BAM'),
        ('Barbados', 'BB', 'BRB', '052', '["1246"]', 'North America', 'America/Barbados', 'BBD'),
        ('Bangladesh', 'BD', 'BGD', '050', '["880"]', 'Asia', 'Asia/Dhaka', 'BDT'),
        ('Belgium', 'BE', 'BEL', '056', '["32"]', 'Europe', 'Europe/Brussels', 'EUR'),
        ('Burkina Faso', 'BF', 'BFA', '854', '["226"]', 'Africa', 'Africa/Ouagadougou', 'XOF'),
        ('Bulgaria', 'BG', 'BGR', '100', '["359"]', 'Europe', 'Europe/Sofia', 'EUR'),
        ('Bahrain', 'BH', 'BHR', '048', '["973"]', 'Asia', 'Asia/Qatar', 'BHD'),
        ('Burundi', 'BI', 'BDI', '108', '["257"]', 'Africa', 'Africa/Maputo', 'BIF'),
        ('Benin', 'BJ', 'BEN', '204', '["229"]', 'Africa', 'Africa/Porto-Novo', 'XOF'),
        ('Saint Barthelemy', 'BL', 'BLM', '652', '["590"]', 'North America', 'America/Puerto_Rico', 'EUR'),
        ('Bermuda', 'BM', 'BMU', '060', '["1441"]', 'North America', 'Atlantic/Bermuda', 'BMD'),
        ('Brunei', 'BN', 'BRN', '096', '["673"]', 'Asia', 'Asia/Kuching', 'BND'),
        ('Bolivia', 'BO', 'BOL', '068', '["591"]', 'South America', 'America/La_Paz', 'BOB'),
        ('Bonaire', 'BQ', 'BES', '535', '["5997"]', 'North America', 'America/Kralendijk', 'USD'),
        ('Brazil', 'BR', 'BRA', '076', '["55"]', 'South America', 'America/Sao_Paulo', 'BRL'),
        ('Bahamas', 'BS', 'BHS', '044', '["1242"]', 'North America', 'America/Nassau', 'BSD'),
        ('Bhutan', 'BT', 'BTN', '064', '["975"]', 'Asia', 'Asia/Thimphu', 'BTN'),
        ('Bouvet Island', 'BV', 'BVT', '074', '["47"]', 'Antarctica', 'UTC', 'NOK'),
        ('Botswana', 'BW', 'BWA', '072', '["267"]', 'Africa', 'Africa/Gaborone', 'BWP'),
        ('Belarus', 'BY', 'BLR', '112', '["375"]', 'Europe', 'Europe/Minsk', 'BYN'),
        ('Belize', 'BZ', 'BLZ', '084', '["501"]', 'North America', 'America/Belize', 'BZD'),
        ('Canada', 'CA', 'CAN', '124', '["1"]', 'North America', 'America/Toronto', 'CAD'),
        ('Cocos (Keeling) Islands', 'CC', 'CCK', '166', '["61"]', 'Asia', 'Asia/Yangon', 'AUD'),
        ('Democratic Republic of the Congo', 'CD', 'COD', '180', '["243"]', 'Africa', 'Africa/Kinshasa', 'CDF'),
        ('Central African Republic', 'CF', 'CAF', '140', '["236"]', 'Africa', 'Africa/Bangui', 'XAF'),
        ('Republic of the Congo', 'CG', 'COG', '178', '["242"]', 'Africa', 'Africa/Brazzaville', 'XAF'),
        ('Switzerland', 'CH', 'CHE', '756', '["41"]', 'Europe', 'Europe/Zurich', 'CHF'),
        ('Ivory Coast', 'CI', 'CIV', '384', '["225"]', 'Africa', 'Africa/Abidjan', 'XOF'),
        ('Cook Islands', 'CK', 'COK', '184', '["682"]', 'Oceania', 'Pacific/Rarotonga', 'NZD'),
        ('Chile', 'CL', 'CHL', '152', '["56"]', 'South America', 'America/Santiago', 'CLP'),
        ('Cameroon', 'CM', 'CMR', '120', '["237"]', 'Africa', 'Africa/Lagos', 'XAF'),
        ('China', 'CN', 'CHN', '156', '["86"]', 'Asia', 'Asia/Shanghai', 'CNY'),
        ('Colombia', 'CO', 'COL', '170', '["57"]', 'South America', 'America/Bogota', 'COP'),
        ('Costa Rica', 'CR', 'CRI', '188', '["506"]', 'North America', 'America/Costa_Rica', 'CRC'),
        ('Cuba', 'CU', 'CUB', '192', '["53"]', 'North America', 'America/Havana', 'CUP'),
        ('Cabo Verde', 'CV', 'CPV', '132', '["238"]', 'Africa', 'Atlantic/Cape_Verde', 'CVE'),
        ('Curacao', 'CW', 'CUW', '531', '["5999"]', 'North America', 'America/Puerto_Rico', 'XCG'),
        ('Christmas Island', 'CX', 'CXR', '162', '["61"]', 'Asia', 'Asia/Bangkok', 'AUD'),
        ('Cyprus', 'CY', 'CYP', '196', '["357"]', 'Europe', 'Asia/Nicosia', 'EUR'),
        ('Czechia', 'CZ', 'CZE', '203', '["420"]', 'Europe', 'Europe/Prague', 'CZK'),
        ('Germany', 'DE', 'DEU', '276', '["49"]', 'Europe', 'Europe/Berlin', 'EUR'),
        ('Djibouti', 'DJ', 'DJI', '262', '["253"]', 'Africa', 'Africa/Djibouti', 'DJF'),
        ('Denmark', 'DK', 'DNK', '208', '["45"]', 'Europe', 'Europe/Copenhagen', 'DKK'),
        ('Dominica', 'DM', 'DMA', '212', '["1767"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Dominican Republic', 'DO', 'DOM', '214', '["1809","1829","1849"]', 'North America', 'America/Santo_Domingo', 'DOP'),
        ('Algeria', 'DZ', 'DZA', '012', '["213"]', 'Africa', 'Africa/Algiers', 'DZD'),
        ('Ecuador', 'EC', 'ECU', '218', '["593"]', 'South America', 'America/Guayaquil', 'USD'),
        ('Estonia', 'EE', 'EST', '233', '["372"]', 'Europe', 'Europe/Tallinn', 'EUR'),
        ('Egypt', 'EG', 'EGY', '818', '["20"]', 'Africa', 'Africa/Cairo', 'EGP'),
        ('Western Sahara', 'EH', 'ESH', '732', '["212"]', 'Africa', 'Africa/El_Aaiun', 'MAD'),
        ('Eritrea', 'ER', 'ERI', '232', '["291"]', 'Africa', 'Africa/Asmara', 'ERN'),
        ('Spain', 'ES', 'ESP', '724', '["34"]', 'Europe', 'Europe/Madrid', 'EUR'),
        ('Ethiopia', 'ET', 'ETH', '231', '["251"]', 'Africa', 'Africa/Addis_Ababa', 'ETB'),
        ('Finland', 'FI', 'FIN', '246', '["358"]', 'Europe', 'Europe/Helsinki', 'EUR'),
        ('Fiji', 'FJ', 'FJI', '242', '["679"]', 'Oceania', 'Pacific/Fiji', 'FJD'),
        ('Falkland Islands', 'FK', 'FLK', '238', '["500"]', 'South America', 'Atlantic/Stanley', 'FKP'),
        ('Micronesia', 'FM', 'FSM', '583', '["691"]', 'Oceania', 'Pacific/Kosrae', 'USD'),
        ('Faroe Islands', 'FO', 'FRO', '234', '["298"]', 'Europe', 'Atlantic/Faroe', 'DKK'),
        ('France', 'FR', 'FRA', '250', '["33"]', 'Europe', 'Europe/Paris', 'EUR'),
        ('Gabon', 'GA', 'GAB', '266', '["241"]', 'Africa', 'Africa/Libreville', 'XAF'),
        ('United Kingdom', 'GB', 'GBR', '826', '["44"]', 'Europe', 'Europe/London', 'GBP'),
        ('Grenada', 'GD', 'GRD', '308', '["1473"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Georgia', 'GE', 'GEO', '268', '["995"]', 'Asia', 'Asia/Tbilisi', 'GEL'),
        ('French Guiana', 'GF', 'GUF', '254', '["594"]', 'South America', 'America/Cayenne', 'EUR'),
        ('Guernsey', 'GG', 'GGY', '831', '["44"]', 'Europe', 'Europe/London', 'GBP'),
        ('Ghana', 'GH', 'GHA', '288', '["233"]', 'Africa', 'Africa/Accra', 'GHS'),
        ('Gibraltar', 'GI', 'GIB', '292', '["350"]', 'Europe', 'Europe/Gibraltar', 'GIP'),
        ('Greenland', 'GL', 'GRL', '304', '["299"]', 'North America', 'America/Nuuk', 'DKK'),
        ('Gambia', 'GM', 'GMB', '270', '["220"]', 'Africa', 'Africa/Banjul', 'GMD'),
        ('Guinea', 'GN', 'GIN', '324', '["224"]', 'Africa', 'Africa/Conakry', 'GNF'),
        ('Guadeloupe', 'GP', 'GLP', '312', '["590"]', 'North America', 'America/Puerto_Rico', 'EUR'),
        ('Equatorial Guinea', 'GQ', 'GNQ', '226', '["240"]', 'Africa', 'Africa/Malabo', 'XAF'),
        ('Greece', 'GR', 'GRC', '300', '["30"]', 'Europe', 'Europe/Athens', 'EUR'),
        ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', '["500"]', 'Antarctica', 'Atlantic/South_Georgia', 'GBP'),
        ('Guatemala', 'GT', 'GTM', '320', '["502"]', 'North America', 'America/Guatemala', 'GTQ'),
        ('Guam', 'GU', 'GUM', '316', '["1671"]', 'Oceania', 'Pacific/Guam', 'USD'),
        ('Guinea-Bissau', 'GW', 'GNB', '624', '["245"]', 'Africa', 'Africa/Bissau', 'XOF'),
        ('Guyana', 'GY', 'GUY', '328', '["592"]', 'South America', 'America/Guyana', 'GYD'),
        ('Hong Kong', 'HK', 'HKG', '344', '["852"]', 'Asia', 'Asia/Hong_Kong', 'HKD'),
        ('Heard Island and McDonald Islands', 'HM', 'HMD', '334', '["61"]', 'Antarctica', 'UTC', 'AUD'),
        ('Honduras', 'HN', 'HND', '340', '["504"]', 'North America', 'America/Tegucigalpa', 'HNL'),
        ('Croatia', 'HR', 'HRV', '191', '["385"]', 'Europe', 'Europe/Zagreb', 'EUR'),
        ('Haiti', 'HT', 'HTI', '332', '["509"]', 'North America', 'America/Port-au-Prince', 'HTG'),
        ('Hungary', 'HU', 'HUN', '348', '["36"]', 'Europe', 'Europe/Budapest', 'HUF'),
        ('Indonesia', 'ID', 'IDN', '360', '["62"]', 'Asia', 'Asia/Jakarta', 'IDR'),
        ('Ireland', 'IE', 'IRL', '372', '["353"]', 'Europe', 'Europe/Dublin', 'EUR'),
        ('Israel', 'IL', 'ISR', '376', '["972"]', 'Asia', 'Asia/Jerusalem', 'ILS'),
        ('Isle of Man', 'IM', 'IMN', '833', '["44"]', 'Europe', 'Europe/London', 'GBP'),
        ('India', 'IN', 'IND', '356', '["91"]', 'Asia', 'Asia/Kolkata', 'INR'),
        ('British Indian Ocean Territory', 'IO', 'IOT', '086', '["246"]', 'Asia', 'Indian/Chagos', 'USD'),
        ('Iraq', 'IQ', 'IRQ', '368', '["964"]', 'Asia', 'Asia/Baghdad', 'IQD'),
        ('Iran', 'IR', 'IRN', '364', '["98"]', 'Asia', 'Asia/Tehran', 'IRR'),
        ('Iceland', 'IS', 'ISL', '352', '["354"]', 'Europe', 'Atlantic/Reykjavik', 'ISK'),
        ('Italy', 'IT', 'ITA', '380', '["39"]', 'Europe', 'Europe/Rome', 'EUR'),
        ('Jersey', 'JE', 'JEY', '832', '["44"]', 'Europe', 'Europe/London', 'GBP'),
        ('Jamaica', 'JM', 'JAM', '388', '["1876"]', 'North America', 'America/Jamaica', 'JMD'),
        ('Jordan', 'JO', 'JOR', '400', '["962"]', 'Asia', 'Asia/Amman', 'JOD'),
        ('Japan', 'JP', 'JPN', '392', '["81"]', 'Asia', 'Asia/Tokyo', 'JPY'),
        ('Kenya', 'KE', 'KEN', '404', '["254"]', 'Africa', 'Africa/Nairobi', 'KES'),
        ('Kyrgyzstan', 'KG', 'KGZ', '417', '["996"]', 'Asia', 'Asia/Bishkek', 'KGS'),
        ('Cambodia', 'KH', 'KHM', '116', '["855"]', 'Asia', 'Asia/Phnom_Penh', 'KHR'),
        ('Kiribati', 'KI', 'KIR', '296', '["686"]', 'Oceania', 'Pacific/Tarawa', 'AUD'),
        ('Comoros', 'KM', 'COM', '174', '["269"]', 'Africa', 'Africa/Nairobi', 'KMF'),
        ('Saint Kitts and Nevis', 'KN', 'KNA', '659', '["1869"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('North Korea', 'KP', 'PRK', '408', '["850"]', 'Asia', 'Asia/Pyongyang', 'KPW'),
        ('South Korea', 'KR', 'KOR', '410', '["82"]', 'Asia', 'Asia/Seoul', 'KRW'),
        ('Kuwait', 'KW', 'KWT', '414', '["965"]', 'Asia', 'Asia/Riyadh', 'KWD'),
        ('Cayman Islands', 'KY', 'CYM', '136', '["1345"]', 'North America', 'America/Panama', 'KYD'),
        ('Kazakhstan', 'KZ', 'KAZ', '398', '["7"]', 'Asia', 'Asia/Almaty', 'KZT'),
        ('Laos', 'LA', 'LAO', '418', '["856"]', 'Asia', 'Asia/Vientiane', 'LAK'),
        ('Lebanon', 'LB', 'LBN', '422', '["961"]', 'Asia', 'Asia/Beirut', 'LBP'),
        ('Saint Lucia', 'LC', 'LCA', '662', '["1758"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Liechtenstein', 'LI', 'LIE', '438', '["423"]', 'Europe', 'Europe/Vaduz', 'CHF'),
        ('Sri Lanka', 'LK', 'LKA', '144', '["94"]', 'Asia', 'Asia/Colombo', 'LKR'),
        ('Liberia', 'LR', 'LBR', '430', '["231"]', 'Africa', 'Africa/Monrovia', 'LRD'),
        ('Lesotho', 'LS', 'LSO', '426', '["266"]', 'Africa', 'Africa/Maseru', 'LSL'),
        ('Lithuania', 'LT', 'LTU', '440', '["370"]', 'Europe', 'Europe/Vilnius', 'EUR'),
        ('Luxembourg', 'LU', 'LUX', '442', '["352"]', 'Europe', 'Europe/Luxembourg', 'EUR'),
        ('Latvia', 'LV', 'LVA', '428', '["371"]', 'Europe', 'Europe/Riga', 'EUR'),
        ('Libya', 'LY', 'LBY', '434', '["218"]', 'Africa', 'Africa/Tripoli', 'LYD'),
        ('Morocco', 'MA', 'MAR', '504', '["212"]', 'Africa', 'Africa/Casablanca', 'MAD'),
        ('Monaco', 'MC', 'MCO', '492', '["377"]', 'Europe', 'Europe/Monaco', 'EUR'),
        ('Moldova', 'MD', 'MDA', '498', '["373"]', 'Europe', 'Europe/Chisinau', 'MDL'),
        ('Montenegro', 'ME', 'MNE', '499', '["382"]', 'Europe', 'Europe/Podgorica', 'EUR'),
        ('Saint Martin', 'MF', 'MAF', '663', '["590"]', 'North America', 'America/Marigot', 'EUR'),
        ('Madagascar', 'MG', 'MDG', '450', '["261"]', 'Africa', 'Indian/Antananarivo', 'MGA'),
        ('Marshall Islands', 'MH', 'MHL', '584', '["692"]', 'Oceania', 'Pacific/Majuro', 'USD'),
        ('North Macedonia', 'MK', 'MKD', '807', '["389"]', 'Europe', 'Europe/Skopje', 'MKD'),
        ('Mali', 'ML', 'MLI', '466', '["223"]', 'Africa', 'Africa/Bamako', 'XOF'),
        ('Myanmar', 'MM', 'MMR', '104', '["95"]', 'Asia', 'Asia/Yangon', 'MMK'),
        ('Mongolia', 'MN', 'MNG', '496', '["976"]', 'Asia', 'Asia/Ulaanbaatar', 'MNT'),
        ('Macao', 'MO', 'MAC', '446', '["853"]', 'Asia', 'Asia/Macau', 'MOP'),
        ('Northern Mariana Islands', 'MP', 'MNP', '580', '["1670"]', 'Oceania', 'Pacific/Saipan', 'USD'),
        ('Martinique', 'MQ', 'MTQ', '474', '["596"]', 'North America', 'America/Martinique', 'EUR'),
        ('Mauritania', 'MR', 'MRT', '478', '["222"]', 'Africa', 'Africa/Nouakchott', 'MRU'),
        ('Montserrat', 'MS', 'MSR', '500', '["1664"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Malta', 'MT', 'MLT', '470', '["356"]', 'Europe', 'Europe/Malta', 'EUR'),
        ('Mauritius', 'MU', 'MUS', '480', '["230"]', 'Africa', 'Indian/Mauritius', 'MUR'),
        ('Maldives', 'MV', 'MDV', '462', '["960"]', 'Asia', 'Indian/Maldives', 'MVR'),
        ('Malawi', 'MW', 'MWI', '454', '["265"]', 'Africa', 'Africa/Maputo', 'MWK'),
        ('Mexico', 'MX', 'MEX', '484', '["52"]', 'North America', 'America/Mexico_City', 'MXN'),
        ('Malaysia', 'MY', 'MYS', '458', '["60"]', 'Asia', 'Asia/Kuala_Lumpur', 'MYR'),
        ('Mozambique', 'MZ', 'MOZ', '508', '["258"]', 'Africa', 'Africa/Maputo', 'MZN'),
        ('Namibia', 'NA', 'NAM', '516', '["264"]', 'Africa', 'Africa/Windhoek', 'NAD'),
        ('New Caledonia', 'NC', 'NCL', '540', '["687"]', 'Oceania', 'Pacific/Noumea', 'XPF'),
        ('Niger', 'NE', 'NER', '562', '["227"]', 'Africa', 'Africa/Niamey', 'XOF'),
        ('Norfolk Island', 'NF', 'NFK', '574', '["672"]', 'Oceania', 'Pacific/Norfolk', 'AUD'),
        ('Nigeria', 'NG', 'NGA', '566', '["234"]', 'Africa', 'Africa/Lagos', 'NGN'),
        ('Nicaragua', 'NI', 'NIC', '558', '["505"]', 'North America', 'America/Managua', 'NIO'),
        ('Netherlands', 'NL', 'NLD', '528', '["31"]', 'Europe', 'Europe/Amsterdam', 'EUR'),
        ('Norway', 'NO', 'NOR', '578', '["47"]', 'Europe', 'Europe/Oslo', 'NOK'),
        ('Nepal', 'NP', 'NPL', '524', '["977"]', 'Asia', 'Asia/Kathmandu', 'NPR'),
        ('Nauru', 'NR', 'NRU', '520', '["674"]', 'Oceania', 'Pacific/Nauru', 'AUD'),
        ('Niue', 'NU', 'NIU', '570', '["683"]', 'Oceania', 'Pacific/Niue', 'NZD'),
        ('New Zealand', 'NZ', 'NZL', '554', '["64"]', 'Oceania', 'Pacific/Auckland', 'NZD'),
        ('Oman', 'OM', 'OMN', '512', '["968"]', 'Asia', 'Asia/Muscat', 'OMR'),
        ('Panama', 'PA', 'PAN', '591', '["507"]', 'North America', 'America/Panama', 'PAB'),
        ('Peru', 'PE', 'PER', '604', '["51"]', 'South America', 'America/Lima', 'PEN'),
        ('French Polynesia', 'PF', 'PYF', '258', '["689"]', 'Oceania', 'Pacific/Tahiti', 'XPF'),
        ('Papua New Guinea', 'PG', 'PNG', '598', '["675"]', 'Oceania', 'Pacific/Port_Moresby', 'PGK'),
        ('Philippines', 'PH', 'PHL', '608', '["63"]', 'Asia', 'Asia/Manila', 'PHP'),
        ('Pakistan', 'PK', 'PAK', '586', '["92"]', 'Asia', 'Asia/Karachi', 'PKR'),
        ('Poland', 'PL', 'POL', '616', '["48"]', 'Europe', 'Europe/Warsaw', 'PLN'),
        ('Saint Pierre and Miquelon', 'PM', 'SPM', '666', '["508"]', 'North America', 'America/Miquelon', 'EUR'),
        ('Pitcairn Islands', 'PN', 'PCN', '612', '["64"]', 'Oceania', 'Pacific/Pitcairn', 'NZD'),
        ('Puerto Rico', 'PR', 'PRI', '630', '["1787","1939"]', 'North America', 'America/Puerto_Rico', 'USD'),
        ('Palestine', 'PS', 'PSE', '275', '["970"]', 'Asia', 'Asia/Gaza', 'ILS'),
        ('Portugal', 'PT', 'PRT', '620', '["351"]', 'Europe', 'Europe/Lisbon', 'EUR'),
        ('Palau', 'PW', 'PLW', '585', '["680"]', 'Oceania', 'Pacific/Palau', 'USD'),
        ('Paraguay', 'PY', 'PRY', '600', '["595"]', 'South America', 'America/Asuncion', 'PYG'),
        ('Qatar', 'QA', 'QAT', '634', '["974"]', 'Asia', 'Asia/Qatar', 'QAR'),
        ('Reunion', 'RE', 'REU', '638', '["262"]', 'Africa', 'Asia/Dubai', 'EUR'),
        ('Romania', 'RO', 'ROU', '642', '["40"]', 'Europe', 'Europe/Bucharest', 'RON'),
        ('Serbia', 'RS', 'SRB', '688', '["381"]', 'Europe', 'Europe/Belgrade', 'RSD'),
        ('Russia', 'RU', 'RUS', '643', '["7"]', 'Europe', 'Europe/Moscow', 'RUB'),
        ('Rwanda', 'RW', 'RWA', '646', '["250"]', 'Africa', 'Africa/Kigali', 'RWF'),
        ('Saudi Arabia', 'SA', 'SAU', '682', '["966"]', 'Asia', 'Asia/Riyadh', 'SAR'),
        ('Solomon Islands', 'SB', 'SLB', '090', '["677"]', 'Oceania', 'Pacific/Guadalcanal', 'SBD'),
        ('Seychelles', 'SC', 'SYC', '690', '["248"]', 'Africa', 'Asia/Dubai', 'SCR'),
        ('Sudan', 'SD', 'SDN', '729', '["249"]', 'Africa', 'Africa/Khartoum', 'SDG'),
        ('Sweden', 'SE', 'SWE', '752', '["46"]', 'Europe', 'Europe/Stockholm', 'SEK'),
        ('Singapore', 'SG', 'SGP', '702', '["65"]', 'Asia', 'Asia/Singapore', 'SGD'),
        ('Saint Helena', 'SH', 'SHN', '654', '["290"]', 'Africa', 'Africa/Abidjan', 'SHP'),
        ('Slovenia', 'SI', 'SVN', '705', '["386"]', 'Europe', 'Europe/Ljubljana', 'EUR'),
        ('Svalbard and Jan Mayen', 'SJ', 'SJM', '744', '["4779"]', 'Europe', 'Arctic/Longyearbyen', 'NOK'),
        ('Slovakia', 'SK', 'SVK', '703', '["421"]', 'Europe', 'Europe/Bratislava', 'EUR'),
        ('Sierra Leone', 'SL', 'SLE', '694', '["232"]', 'Africa', 'Africa/Freetown', 'SLE'),
        ('San Marino', 'SM', 'SMR', '674', '["378"]', 'Europe', 'Europe/Rome', 'EUR'),
        ('Senegal', 'SN', 'SEN', '686', '["221"]', 'Africa', 'Africa/Dakar', 'XOF'),
        ('Somalia', 'SO', 'SOM', '706', '["252"]', 'Africa', 'Africa/Mogadishu', 'SOS'),
        ('Suriname', 'SR', 'SUR', '740', '["597"]', 'South America', 'America/Paramaribo', 'SRD'),
        ('South Sudan', 'SS', 'SSD', '728', '["211"]', 'Africa', 'Africa/Juba', 'SSP'),
        ('Sao Tome and Principe', 'ST', 'STP', '678', '["239"]', 'Africa', 'Africa/Sao_Tome', 'STN'),
        ('El Salvador', 'SV', 'SLV', '222', '["503"]', 'North America', 'America/El_Salvador', 'USD'),
        ('Sint Maarten', 'SX', 'SXM', '534', '["1721"]', 'North America', 'America/Puerto_Rico', 'XCG'),
        ('Syria', 'SY', 'SYR', '760', '["963"]', 'Asia', 'Asia/Damascus', 'SYP'),
        ('Eswatini', 'SZ', 'SWZ', '748', '["268"]', 'Africa', 'Africa/Johannesburg', 'SZL'),
        ('Turks and Caicos Islands', 'TC', 'TCA', '796', '["1649"]', 'North America', 'America/Grand_Turk', 'USD'),
        ('Chad', 'TD', 'TCD', '148', '["235"]', 'Africa', 'Africa/Ndjamena', 'XAF'),
        ('French Southern Territories', 'TF', 'ATF', '260', '["262"]', 'Antarctica', 'Asia/Dubai', 'EUR'),
        ('Togo', 'TG', 'TGO', '768', '["228"]', 'Africa', 'Africa/Abidjan', 'XOF'),
        ('Thailand', 'TH', 'THA', '764', '["66"]', 'Asia', 'Asia/Bangkok', 'THB'),
        ('Tajikistan', 'TJ', 'TJK', '762', '["992"]', 'Asia', 'Asia/Dushanbe', 'TJS'),
        ('Tokelau', 'TK', 'TKL', '772', '["690"]', 'Oceania', 'Pacific/Fakaofo', 'NZD'),
        ('East Timor', 'TL', 'TLS', '626', '["670"]', 'Oceania', 'Asia/Dili', 'USD'),
        ('Turkmenistan', 'TM', 'TKM', '795', '["993"]', 'Asia', 'Asia/Ashgabat', 'TMT'),
        ('Tunisia', 'TN', 'TUN', '788', '["216"]', 'Africa', 'Africa/Tunis', 'TND'),
        ('Tonga', 'TO', 'TON', '776', '["676"]', 'Oceania', 'Pacific/Tongatapu', 'TOP'),
        ('Türkiye', 'TR', 'TUR', '792', '["90"]', 'Asia', 'Europe/Istanbul', 'TRY'),
        ('Trinidad and Tobago', 'TT', 'TTO', '780', '["1868"]', 'North America', 'America/Port_of_Spain', 'TTD'),
        ('Tuvalu', 'TV', 'TUV', '798', '["688"]', 'Oceania', 'Pacific/Funafuti', 'AUD'),
        ('Taiwan', 'TW', 'TWN', '158', '["886"]', 'Asia', 'Asia/Taipei', 'TWD'),
        ('Tanzania', 'TZ', 'TZA', '834', '["255"]', 'Africa', 'Africa/Nairobi', 'TZS'),
        ('Ukraine', 'UA', 'UKR', '804', '["380"]', 'Europe', 'Europe/Kyiv', 'UAH'),
        ('Uganda', 'UG', 'UGA', '800', '["256"]', 'Africa', 'Africa/Kampala', 'UGX'),
        ('U.S. Minor Outlying Islands', 'UM', 'UMI', '581', '["1"]', 'Oceania', 'Pacific/Pago_Pago', 'USD'),
        ('United States', 'US', 'USA', '840', '["1"]', 'North America', 'America/New_York', 'USD'),
        ('Uruguay', 'UY', 'URY', '858', '["598"]', 'South America', 'America/Montevideo', 'UYU'),
        ('Uzbekistan', 'UZ', 'UZB', '860', '["998"]', 'Asia', 'Asia/Tashkent', 'UZS'),
        ('Vatican City', 'VA', 'VAT', '336', '["379"]', 'Europe', 'Europe/Rome', 'EUR'),
        ('Saint Vincent and the Grenadines', 'VC', 'VCT', '670', '["1784"]', 'North America', 'America/Puerto_Rico', 'XCD'),
        ('Venezuela', 'VE', 'VEN', '862', '["58"]', 'South America', 'America/Caracas', 'VES'),
        ('British Virgin Islands', 'VG', 'VGB', '092', '["1284"]', 'North America', 'America/Puerto_Rico', 'USD'),
        ('U.S. Virgin Islands', 'VI', 'VIR', '850', '["1340"]', 'North America', 'America/Puerto_Rico', 'USD'),
        ('Vietnam', 'VN', 'VNM', '704', '["84"]', 'Asia', 'Asia/Ho_Chi_Minh', 'VND'),
        ('Vanuatu', 'VU', 'VUT', '548', '["678"]', 'Oceania', 'Pacific/Efate', 'VUV'),
        ('Wallis and Futuna', 'WF', 'WLF', '876', '["681"]', 'Oceania', 'Pacific/Tarawa', 'XPF'),
        ('Samoa', 'WS', 'WSM', '882', '["685"]', 'Oceania', 'Pacific/Apia', 'WST'),
        ('Kosovo', 'XK', 'XKK', '983', '["377","381","383","386"]', 'Europe', 'UTC', 'EUR'),
        ('Yemen', 'YE', 'YEM', '887', '["967"]', 'Asia', 'Asia/Riyadh', 'YER'),
        ('Mayotte', 'YT', 'MYT', '175', '["262"]', 'Africa', 'Africa/Nairobi', 'EUR'),
        ('South Africa', 'ZA', 'ZAF', '710', '["27"]', 'Africa', 'Africa/Johannesburg', 'ZAR'),
        ('Zambia', 'ZM', 'ZMB', '894', '["260"]', 'Africa', 'Africa/Lusaka', 'ZMW'),
        ('Zimbabwe', 'ZW', 'ZWE', '716', '["263"]', 'Africa', 'Africa/Harare', 'ZWG')
    on conflict do nothing;`);
  }

  override async down(): Promise<void> {
    // Irreversible on purpose: users reference countries, and there is no
    // telling which rows existed before this ran.
  }

}
