// Every editable field the update endpoint accepts, excluding the token
// caps and status (not editable here).
export const CHATBOT_EDITABLE_FIELDS = [
    'name',
    'accounts',
    'avatar',
    'generalKnowledge',
    'agentProfile',
    'extraInstructions',
    'type',
    'autoRead',
    'typingIndicator',
    'modelTextName',
    'primaryLanguage',
    'deferedLanguage',
    'welcomeMessage',
    'fallbackMessage',
    'modelTemperature',
    'maxTokens',
    'guardrailEnabled',
    'guardrailModelEnabled',
    'guardrailCustomInstruction',
    'guardrailEscalateOnBlock',
    'handoffFallbackThreshold',
    'handoffMessage',
    'handoffKeywords',
    'followupRules',
] as const;
