import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
    IsDefined,
    IsNotEmpty,
    IsOptional,
    IsString,
    Matches,
    MaxLength,
} from 'class-validator';

export class ChatbotStreamRequestDto {
    @ApiProperty({
        description: 'The user message to send to the chatbot',
        example: 'What are my pending orders?',
    })
    @IsDefined()
    @IsNotEmpty()
    @IsString()
    // Bounds the per-turn prompt cost. Rejected, never truncated, so an
    // oversized message fails loudly instead of silently losing context.
    @MaxLength(2000)
    message: string;

    @ApiPropertyOptional({
        description:
            'Chat session ID to continue an existing conversation. Generated by the client (the AI SDK), so not a UUID.',
        example: 'ETDBmNUSBlXcVcLz',
    })
    @IsOptional()
    // The AI SDK's `useChat` mints this id itself and it is NOT a UUID (it is a
    // short nanoid, e.g. "ETDBmNUSBlXcVcLz"). The value is sha256-hashed before
    // it becomes a Redis key, so this bounds the input rather than protecting
    // the key space.
    @Matches(/^[A-Za-z0-9_-]{1,64}$/)
    chat_session_id?: string;
}
