import { ApiProperty } from '@nestjs/swagger';
import { IsDate, IsString } from 'class-validator';

export class CreateInvitationRequestDto {
    @ApiProperty({
        description: "Workspace's id",
    })
    @IsString()
    workspace: string;

    @ApiProperty({
        description: "User's id",
    })
    @IsString()
    user: string;

    @ApiProperty({
        description: "Role's id",
    })
    @IsString()
    role?: string;

    @ApiProperty({
        description: 'Email address to invite',
    })
    email: string;

    @ApiProperty({
        description: 'Expiration time for the invitation link',
    })
    @IsDate()
    expiresAt: Date;

    @ApiProperty({
        description: 'Invitation link. (Should be generated by server only)',
    })
    invitationLink: string;

    @ApiProperty({
        description: 'Invitation token. (Should be generated by server only)',
    })
    token: string;
}
