from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


class AttachmentData(BaseModel):
    attachment_id: str = Field(..., description="The unique identifier of the attachment.")
    preview_url: Optional[str] = Field(default=None, description="A URL for previewing the attachment, if applicable.")


class ActionEditableForm(BaseModel):
    field_name: str = Field(..., description="The unique identifier of the form field.")
    value: Any = Field(default=None, description="The value of the form field, if applicable.")


class ActionDataRequest(BaseModel):
    selected_option: Optional[str] = Field(default=None, description="The unique identifier of the selected action option, if applicable.")
    updated_form: Optional[list[ActionEditableForm]] = Field(default=None, description="A dictionary containing form field ids and their corresponding user input values, if applicable.")


class ActionDataResponse(BaseModel):
    options: Optional[list[str]] = Field(default=None, description="A list of action options for the user to choose from, if applicable.")
    preview_form: Optional[list[ActionEditableForm]] = Field(default=None, description="A list of form items for form-based actions.")


class ChatHistoryMessage(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(..., description="Who authored this turn.")
    content: str = Field(..., description="The message text.")


class ChatRequest(BaseModel):
    """
    ChatRequestData represents the data required to process a chat request, including the user's message and any relevant metadata.
    """
    chatbot_id: str = Field(..., description="The unique identifier of the chatbot config.")
    message: Optional[str] = Field(None, description="The user's message to be processed by the chat agent.")
    history: Optional[list[ChatHistoryMessage]] = Field(default=None, description="Prior conversation turns injected by apps/api (the message source of truth). The agent is stateless, so context is supplied each request.")
    attachments: Optional[list[AttachmentData]] = Field(None, description="A list of attachment ids or identifiers associated with the message.")
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID to maintain context across multiple messages, if applicable.")
    user_id: Optional[str] = Field(default=None, description="Useful for personalization and context management.")
    provider_id: Optional[str] = Field(default=None, description="The provider/agent handling the chat request (apps/api account id).")
    action: Optional[ActionDataRequest] = Field(None, description="Action data if the message is a response to a previous action.")
    chat_session_id: Optional[str] = Field(None, description="The unique identifier of the chat session, created if not provided.")
    customer_id: Optional[str] = Field(None, description="The Customer record the sender resolves to (apps/api).")
    contact_point_id: Optional[str] = Field(None, description="The ContactPoint linking sender→Customer (apps/api).")
    trigger_message_id: Optional[str] = Field(default=None, description="apps/api message id that triggered this turn; attached to a scheduled followup so the UI can link back.")


class ChatResponse(BaseModel):
    response: str = Field(..., description="The response message generated by the chat agent.")
    attachments: Optional[list[AttachmentData]] = Field(default=None, description="A list of attachment ids or identifiers associated with the response, if any.")
    metadata: Optional[dict[str, Any]] = Field(default=None, description="Additional metadata related to the chat response, if any.")
