export enum ENUM_CHATBOT_STATUS_CODE_ERROR {
    SHARE_LINK_INVALID = 5410,
    SHARE_LINK_EXPIRED = 5411,
    SHARE_LINK_NOT_CONFIGURED = 5412,
    PREVIEW_NOT_AVAILABLE = 5413,
    PREVIEW_SESSION_LIMIT = 5414,
    ACCOUNTS_NOT_FOUND = 5415,
}
