export enum ENUM_CHATBOT_STATUS {
    ACTIVE = 'active',
    INACTIVE = 'inactive',
    ARCHIVED = 'archived',
}

export enum ENUM_CHATBOT_TYPE {
    BEAUTY = 'beauty',
    FASHION = 'fashion',
    RESTAURANT = 'restaurant',
    ECOMMERCE = 'ecommerce',
    HEALTHCARE = 'healthcare',
    FINANCE = 'finance',
    EDUCATION = 'education',
    TRAVEL = 'travel',
    SPA = 'spa',
    FITNESS = 'fitness',
    AUTOMOTIVE = 'automotive',
    REAL_ESTATE = 'real_estate',
    ENTERTAINMENT = 'entertainment',
    OTHER = 'other',
}

export enum ENUM_CHATBOT_LANGUAGE {
    AR = 'ar',
    BN = 'bn',
    BG = 'bg',
    ZH = 'zh',
    HR = 'hr',
    CS = 'cs',
    DA = 'da',
    NL = 'nl',
    EN = 'en',
    ET = 'et',
    FI = 'fi',
    FR = 'fr',
    DE = 'de',
    EL = 'el',
    HE = 'he',
    HI = 'hi',
    HU = 'hu',
    ID = 'id',
    IT = 'it',
    JA = 'ja',
    KO = 'ko',
    LV = 'lv',
    LT = 'lt',
    NO = 'no',
    PL = 'pl',
    PT = 'pt',
    RO = 'ro',
    RU = 'ru',
    SR = 'sr',
    SK = 'sk',
    SL = 'sl',
    ES = 'es',
    SW = 'sw',
    SV = 'sv',
    TH = 'th',
    TR = 'tr',
    UK = 'uk',
    VI = 'vi',
}

export enum ENUM_CHATBOT_MODEL_PROVIDER {
    OPENAI = 'openai',
    GOOGLE = 'google',
    ANTHROPIC = 'anthropic',
    DEEPSEEK = 'deepseek',
}
