import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { Inject, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Cache } from 'cache-manager';
import { createHash } from 'crypto';
import { AIChatHistoryMessage } from './chatbot-ai.service';

const KEY_PREFIX = 'chatbot-preview';
const BUDGET_SUFFIX = 'budget';
const TOKEN_BUDGET_TTL_MS = 60 * 60 * 1000;

interface IPreviewSessionRecord {
    messages: AIChatHistoryMessage[];
    /** Set once the session clears a Turnstile challenge. */
    verified?: boolean;
}

interface IPreviewSessionConfig {
    ttlMs: number;
    maxTurns: number;
    maxTotalChars: number;
    maxMessageChars: number;
    maxTurnsPerSession: number;
    maxTurnsPerTokenHourly: number;
}

/**
 * Ephemeral transcript for the chatbot preview chat (issue #80).
 *
 * apps/ai's agent is stateless — `history` on the request is its only memory
 * mechanism — so multi-turn preview needs the transcript kept somewhere. It
 * lives in the global Redis-backed cache with a sliding TTL, never in Postgres:
 * a preview is a throwaway conversation with no inbox, customer or operator.
 *
 * Keys are always derived server-side. `chat_session_id` is generated by the
 * browser, so keying on it alone would let anyone who guesses one read another
 * tenant's transcript.
 */
@Injectable()
export class ChatbotPreviewSessionService {
    private readonly config: IPreviewSessionConfig;

    constructor(
        @Inject(CACHE_MANAGER) private readonly cacheManager: Cache,
        private readonly configService: ConfigService
    ) {
        this.config =
            this.configService.get<IPreviewSessionConfig>('chatbot.session');
    }

    get maxMessageChars(): number {
        return this.config.maxMessageChars;
    }

    private hash(value: string): string {
        return createHash('sha256').update(value).digest('hex').slice(0, 32);
    }

    /** Session key for the authed operator preview. */
    workspaceKey({
        workspaceId,
        chatbotId,
        userId,
        sessionId,
    }: {
        workspaceId: string;
        chatbotId: string;
        userId: string;
        sessionId: string;
    }): string {
        return `${KEY_PREFIX}:${workspaceId}:${chatbotId}:${userId}:${this.hash(sessionId)}`;
    }

    /**
     * Session key for a public share link. Scoped by the token rather than the
     * chatbot, so two links to the same bot never share a transcript.
     */
    publicKey({
        token,
        sessionId,
    }: {
        token: string;
        sessionId: string;
    }): string {
        return `${KEY_PREFIX}:pub:${this.hash(token)}:${this.hash(sessionId)}`;
    }

    private async load(key: string): Promise<IPreviewSessionRecord> {
        const raw = await this.cacheManager.get<string>(key);
        if (!raw) return { messages: [] };
        try {
            const parsed = JSON.parse(raw) as
                | IPreviewSessionRecord
                | AIChatHistoryMessage[];
            // Tolerate the pre-Turnstile shape (a bare message array) so a
            // rolling deploy doesn't drop live sessions.
            if (Array.isArray(parsed)) return { messages: parsed };
            return {
                verified: parsed?.verified === true,
                messages: Array.isArray(parsed?.messages) ? parsed.messages : [],
            };
        } catch {
            // A corrupt entry must degrade to an amnesiac turn, never a 500.
            return { messages: [] };
        }
    }

    private async save(
        key: string,
        record: IPreviewSessionRecord
    ): Promise<void> {
        await this.cacheManager.set(
            key,
            JSON.stringify(record),
            this.config.ttlMs
        );
    }

    async read(key: string): Promise<AIChatHistoryMessage[]> {
        return (await this.load(key)).messages;
    }

    /**
     * Whether this session already cleared a Turnstile challenge. Turnstile
     * tokens are single-use and expire in minutes, so a public preview
     * verifies once and remembers it — challenging every turn would put a
     * widget in front of every message.
     */
    async isVerified(key: string): Promise<boolean> {
        return (await this.load(key)).verified === true;
    }

    async markVerified(key: string): Promise<void> {
        const record = await this.load(key);
        await this.save(key, { ...record, verified: true });
    }

    /**
     * Append one completed exchange. The user and assistant messages are
     * written together so a failed generation can never leave a dangling user
     * turn behind — that would send the model `[user, user]` on the next turn.
     */
    async writeTurn(
        key: string,
        userText: string,
        assistantText: string
    ): Promise<void> {
        if (!assistantText.trim()) return;

        const record = await this.load(key);
        record.messages.push(
            { role: 'user', content: userText },
            { role: 'assistant', content: assistantText }
        );

        await this.save(key, {
            ...record,
            messages: this.trim(record.messages),
        });
    }

    /** Drop oldest turns until both the turn and character budgets fit. */
    private trim(history: AIChatHistoryMessage[]): AIChatHistoryMessage[] {
        let trimmed = history.slice(-this.config.maxTurns * 2);
        while (
            trimmed.length > 2 &&
            trimmed.reduce((n, m) => n + m.content.length, 0) >
                this.config.maxTotalChars
        ) {
            trimmed = trimmed.slice(2);
        }
        return trimmed;
    }

    /**
     * Consume one turn from the per-session budget. This — not IP throttling —
     * is the cost control on the public path: behind a load balancer every
     * anonymous visitor shares the proxy's IP, so `@Throttle` barely bites.
     */
    async claimTurn(key: string): Promise<boolean> {
        return this.claim(
            `${key}:${BUDGET_SUFFIX}`,
            this.config.maxTurnsPerSession,
            this.config.ttlMs
        );
    }

    /** Consume one turn from a share token's hourly budget. */
    async claimTokenTurn(jti: string): Promise<boolean> {
        return this.claim(
            `${KEY_PREFIX}:${BUDGET_SUFFIX}:token:${jti}`,
            this.config.maxTurnsPerTokenHourly,
            TOKEN_BUDGET_TTL_MS
        );
    }

    private async claim(
        key: string,
        limit: number,
        ttlMs: number
    ): Promise<boolean> {
        const used = (await this.cacheManager.get<number>(key)) ?? 0;
        if (used >= limit) return false;
        await this.cacheManager.set(key, used + 1, ttlMs);
        return true;
    }
}
