import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { Inject, Injectable } from '@nestjs/common';
import { Cache } from 'cache-manager';
import { createHash } from 'crypto';

const KEY_PREFIX = 'widget-session';
/** Long enough that a visitor browsing a shop is not re-challenged. */
const VERIFIED_TTL_MS = 12 * 60 * 60 * 1000;

/**
 * Per-visitor session state for the website widget: whether this visitor has
 * cleared Turnstile, and whether the page claiming to embed the widget is on the
 * account's allowlist.
 *
 * Separate from ChatbotPreviewSessionService on purpose. That one stores a
 * transcript, because a preview has no other persistence; a widget conversation
 * lives in Postgres, so all this needs to remember is the gate.
 */
@Injectable()
export class WidgetSessionService {
    constructor(@Inject(CACHE_MANAGER) private readonly cache: Cache) {}

    /**
     * The visitor id is generated by the browser, so keying on it directly would
     * let anyone who guesses one read another visitor's session state. Hashing
     * with the account makes the key unguessable and scoped to one widget.
     */
    sessionKey(accountId: string, visitorId: string): string {
        const digest = createHash('sha256')
            .update(`${accountId}:${visitorId}`)
            .digest('hex')
            .slice(0, 32);
        return `${KEY_PREFIX}:${accountId}:${digest}`;
    }

    async isVerified(sessionKey: string): Promise<boolean> {
        return (await this.cache.get<boolean>(`${sessionKey}:verified`)) === true;
    }

    async markVerified(sessionKey: string): Promise<void> {
        await this.cache.set(`${sessionKey}:verified`, true, VERIFIED_TTL_MS);
    }

    /**
     * Check the page that embedded the widget against the account's allowlist.
     *
     * Advisory, not a security boundary: `claimedOrigin` comes from the widget
     * itself (the iframe reads `document.referrer`), and the `Origin` header on
     * these requests is eccho's own domain, not the customer's — so this cannot
     * be verified server-side. It stops a widget key being casually pasted onto
     * another site. The boundary that browsers actually enforce is the
     * `frame-ancestors` CSP the widget page is served with; the controls that
     * stop abuse are Turnstile and the per-session rate limit.
     */
    isOriginAllowed(
        allowedOrigins: string[],
        claimedOrigin: string | undefined
    ): boolean {
        if (!allowedOrigins?.length || !claimedOrigin) return false;
        let origin: string;
        try {
            origin = new URL(claimedOrigin).origin.toLowerCase();
        } catch {
            return false;
        }
        return allowedOrigins.some(a => a.toLowerCase() === origin);
    }
}
