export enum ENUM_KNOWLEDGE_BASE_ITEM_STATUS {
    DRAFT = 'DRAFT',
    READY = 'READY',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
}
export const ENUM_KNOWLEDGE_BASE_ITEM_STATUSES = Object.values(
    ENUM_KNOWLEDGE_BASE_ITEM_STATUS
);
