export enum REQUEST_TYPE {
    JOIN_WORKSPACE = 'JOIN_WORKSPACE',
    CHANGE_CONFIG = 'CHANGE_CONFIG',
}

export enum REQUEST_STATUS {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
}
